version: '3'
services:
    php:
        build: 
            context: ./
            dockerfile: ./docker/laravel/compiled.Dockerfile
        # image: blokflautijs/hatshop:1.0.0
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    nginx:
        build: 
            context: ./
            dockerfile: ./docker/nginx/compiled.Dockerfile
        # image: blokflautijs/hatshopweb:1.0.0
        ports:
            - ${EXPOSED_SERVER_PORT}:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

