version: '3'
services:

    # Note: .env file variables by default are not passed to the docker container at runtime.
    # The .env file is used for variable substitutions in config files only
    # However I add it using the 'env_file' directive

    php: # With Laravel installer and some extra scripts
        build: ./docker/laravel
        env_file: .env
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./code:/var/www/public

    nginx:
        image: atillay/lemp-nginx
        ports:
            - ${EXPOSED_SERVER_PORT}:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx
            - ./code:/var/www/public

    mysql:
        image: mysql:5.7
        env_file: .env
        volumes:
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
            # In case we want to persist the database data
            #- ./database:/var/lib/mysql

    # Note: Use MySql users for connecting to PMA interface
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${EXPOSED_PMA_PORT}:80
        environment:
            PMA_HOST: mysql
